/*
 * Generated by scripts/avatar-manifest.mjs — do not edit by hand.
 *
 * Which archetypes have a generated avatar in public/archetypes. Everything
 * not listed here renders the drawn emblem from ./drawn.ts, which is a
 * finished state rather than a placeholder.
 */

export const GENERATED_AVATARS: ReadonlySet<string> = new Set([
  "improviser",
  "sized",
  "patient",
  "anchor",
  "metronome",
  "regular",
  "tide",
  "keel",
  "measured",
  "governor",
  "sentinel",
  "bulwark",
  "clockwork",
  "engineer",
  "steward",
  "composed",
]);

export function hasGeneratedAvatar(key: string): boolean {
  return GENERATED_AVATARS.has(key);
}

/** The static path. Immutable once generated, so it is cached hard. */
export function avatarSrc(key: string): string {
  return `/archetypes/${key}.png`;
}
