import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

/**
 * ESLint, at last.
 *
 * The tree already carried `eslint-disable` directives against a linter that
 * was never installed — comments asking a tool that did not exist to be quiet.
 *
 * The rule set is Next's own with two deliberate subtractions, both of which
 * are conventions this codebase has a reason for rather than rules it is
 * dodging:
 *
 * - **`no-html-link-for-pages` is off.** The public ledger puts a dynamic
 *   segment at the root, so every path resolves to a "page" as far as that
 *   rule can tell — including the API routes this tree navigates to with a
 *   real `<a>` on purpose.
 * - **`no-img-element` is off.** Every `<img>` in this tree points at a URL
 *   whose bytes we do not want Next to touch: a company mark from
 *   `/api/logo/[symbol]`, a badge SVG, a rendered card PNG, or an Unsplash
 *   photograph — and Unsplash's terms *require* hotlinking from their CDN, so
 *   `next/image`'s proxy would be a licence violation rather than an
 *   optimisation.
 * - **`alt-text` is off inside `app/og`.** That file's JSX is rendered by
 *   Satori into a PNG. There is no DOM, no screen reader, and no `alt`
 *   attribute in the output.
 */
const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "out/**",
      "public/**",
      "docs/**",
      ".claude/**",
      // Generated by `next build`; its triple-slash reference is Next's own.
      "next-env.d.ts",
    ],
  },
  {
    rules: {
      "@next/next/no-img-element": "off",
      /*
       * **`no-html-link-for-pages` is off**, and the reason is the public
       * ledger. `/@handle` is a dynamic segment at the *root*, so as far as
       * this rule is concerned every path in the app now resolves to a page —
       * including `/api/snaptrade/connect` and `/api/account/export`, which
       * are deliberately plain `<a>` elements because one hands off to an OAuth
       * portal and the other is a file download. Both must be full-document
       * navigations; `<Link />` would break them. The rule cannot tell those
       * apart from a page link any more, so it reports six false positives and
       * no true ones.
       */
      "@next/next/no-html-link-for-pages": "off",
      /*
       * `any` is a warning rather than an error: the SnapTrade and Stripe SDKs
       * hand back loosely typed payloads at the edges, and failing CI over a
       * cast at a boundary we do not own would train people to disable the
       * rule rather than fix the code.
       */
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    files: ["app/og/**"],
    rules: { "jsx-a11y/alt-text": "off" },
  },
];

export default config;
